services:
  - type: web
    name: interes-compuesto
    runtime: node
    plan: free
    buildCommand: npm install && npm --prefix server install && npm run build
    startCommand: npm --prefix server start
    envVars:
      - key: NODE_VERSION
        value: "22"
